[ADD]Sound&Ship
Team3-thu-space-invaders/thu-space-invaders-phase2 pull request #5
Opened 2022-11-29 16:05 UTC by trueu1120

2022-11-30 02:20 UTC, Jeon-sh commented on res/graphics
> +00111000011110001111110011111100111111100111111000111111011111101111111011111100111111000111100000111000
이 부분은 어떤것이 변경3된것인가요?

2022-11-30 02:23 UTC, Jeon-sh approved these changes
확인완료했습니다.

2022-11-30 11:01 UTC, ahyns62 requested changes
작업 디렉토리와 현재 작업 디렉토리가 다르기 때문에 FileNotFoundException에러가 발생하는 경우가 꽤 있는 것 같습니다.  Ship 모양 변경 확인했고, 실행 시 불필요한 코드 주석 처리 해주신 점 좋은 것 같습니다

2022-11-30 11:01 UTC, ahyns62 commented on src/engine/SoundManager.java
> +}
해당 코드를 실행시켜보니 FileNotFoundException 에러가 떠서 소리가 안나네요. main.wav 지정된 경로를 찾을 수 없다고 나옵니다. 아래 링크를 참고하시면 두 가지 방안이 있는데, 팀원들 모두 Working Directory 경로를 일일히 변경시키기는 어려우니 Sound 파일 경로를 소스가 동작하는 working directory에 넣는게 어떨까요?

참고 : https://gksdudrb922.tistory.com/181

2022-11-30 15:16 UTC, trueu1120 commented on res/graphics
> +00111000011110001111110011111100111111100111111000111111011111101111111011111100111111000111100000111000
변화 내용은 없는데 줄 바꿈을 업로드 과정에서 코드 수정으로 인식한 거 같습니다.

2022-12-01 06:00 UTC, ahyns62 approved these changes
실행오류 수정사항 확인했습니다!

2022-12-01 06:09 UTC, merged